"""add phone number in users table

Revision ID: 27deda51132b
Revises: b597395acb15
Create Date: 2024-02-18 06:51:21.245338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27deda51132b'
down_revision: Union[str, None] = 'b597395acb15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users1', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users1', 'phone_number')
    # ### end Alembic commands ###
